### ISSUE TITLE
[BUG]某个hook状态栏的功能故障导致系统界面不定时黑屏重启

### ISSUE THREAD

**Issue by Xunflash** [Simplicity-Team/WooBoxForMIUI#235]
**描述一下BUG情况**
手机不定时黑屏 自动重启系统界面 似乎是某个hook状态栏的功能出现问题（推测是MIUI14改动？）

**如何复现**
随机复现 任何时候都有可能发生

**截图**
无法截图

**手机信息：**
 - 设备型号：红米k50至尊版
 - MIUI版本：14.0.23.2.13
 - Android版本：13

**附加信息**
logcat：
[ 2023-02-28T11:52:22.380     1000:  2533:  2533 I/LSPosed-Bridge  ] [E]--> Try to hook [class com.android.systemui.statusbar.phone.NotificationIconContainer][public void com.android.systemui.statusbar.phone.NotificationIconContainer.resetViewStates()] got an Exception [Default]
[ 2023-02-28T11:52:22.380     1000:  2533:  2533 E/LSPosed-Bridge  ] java.lang.IllegalArgumentException: Expected receiver of type android.content.res.AssetManager, but got com.android.systemui.statusbar.phone.NotificationIconContainer
	at java.lang.reflect.Method.invoke(Native Method)
	at q3.c$d$a.a(P:35)
	at q3.c$d$a.c(P:6)
	at p1.c.u0(P:121)
	at p1.c.P(P:1)
	at p1.c$k.d(P:16)
	at p1.c$k.a(P:3)
	at f3.a$a$c.b(P:25)
	at h3.b.a(P:7)
	at g3.d$j.afterHookedMethod(P:12)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.resetViewStates(Unknown Source:8)
	at com.android.systemui.statusbar.phone.NotificationIconContainer.updateState(NotificationIconContainer.java:271)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.updateState(Unknown Source:8)
	at com.android.systemui.statusbar.phone.NotificationIconContainer.onLayout(NotificationIconContainer.java:261)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23867)
	at android.view.ViewGroup.layout(ViewGroup.java:6453)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4176)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3552)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2518)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9389)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
[ 2023-02-28T11:52:22.380     1000:  2533:  2533 E/LSPosed-Bridge  ] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
[ 2023-02-28T11:58:17.435     1000:  2533:  3599 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 2651184 free bytes and 2589KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at h0.U.run(Unknown Source:48)
	at java.util.TimerThread.mainLoop(Timer.java:563)
	at java.util.TimerThread.run(Timer.java:513)
[ 2023-02-28T11:58:18.842     1000: 15739: 15739 I/LSPosed-Bridge  ] Loading module com.fankes.miui.notify from /data/app/~~EjDnhDYt4HKiFJHDKqO_Xg==/com.fankes.miui.notify-ri1c2FbltYLqg1tUWTJV-g==/base.apk
[ 2023-02-28T11:58:18.858     1000: 15739: 15739 I/LSPosed-Bridge  ]   Loading class com.fankes.miui.notify.hook.HookEntry_YukiHookXposedInit
[ 2023-02-28T11:58:18.870     1000: 15739: 15739 I/LSPosed-Bridge  ] Loading module com.gswxxn.restoresplashscreen from /data/app/~~52HcQQ9fSTtfXxK8zQVS2Q==/com.gswxxn.restoresplashscreen-240mpPsHljdr8zRoX0bFvg==/base.apk
[ 2023-02-28T11:58:18.875     1000: 15739: 15739 I/LSPosed-Bridge  ]   Loading class com.gswxxn.restoresplashscreen.hook.HookEntry_YukiHookXposedInit
[ 2023-02-28T11:58:18.882     1000: 15739: 15739 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~dbdyKLmJ1377ramV4nvpdw==/com.lt2333.simplicitytools-jaLEW86zYqcNeOMgte9VSw==/base.apk
[ 2023-02-28T11:58:18.886     1000: 15739: 15739 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hooks.MainHook
[ 2023-02-28T11:58:19.136     1000: 15739: 15739 I/LSPosed-Bridge  ] WooBox: Try to Hook [com.android.systemui]
[ 2023-02-28T11:58:19.163     1000: 15739: 15739 I/LSPosed-Bridge  ] [E/WooBox] Failed to Hook [com.android.systemui]: java.lang.NoSuchMethodException
	at I.a.o(Unknown Source:85)
	at I.a.p(Unknown Source:19)
	at h0.w.a(Unknown Source:47)
	at com.lt2333.simplicitytools.utils.xposed.base.AppRegister.a(Unknown Source:38)
	at com.lt2333.simplicitytools.hooks.apps.SystemUI.handleLoadPackage(Unknown Source:212)
	at com.lt2333.simplicitytools.utils.xposed.EasyXposedInit.handleLoadPackage(Unknown Source:45)
	at com.lt2333.simplicitytools.hooks.MainHook.handleLoadPackage(Unknown Source:11)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at E.afterHookedMethod(Unknown Source:207)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6953)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2212)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
[ 2023-02-28T11:58:21.047    10132: 16205: 16205 I/LSPosed-Bridge  ] Loading module com.gswxxn.unlockmilink from /data/app/~~ONbYyAKa8Fw5wLoAum_dgg==/com.gswxxn.unlockmilink-L6fLtjsHLq0XI6LTEQuqiw==/base.apk
[ 2023-02-28T11:58:21.049    10132: 16205: 16205 I/LSPosed-Bridge  ]   Loading class com.gswxxn.unlockmilink.hook.HookEntry_YukiHookXposedInit
[ 2023-02-28T11:58:21.066    10132: 16205: 16205 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~dbdyKLmJ1377ramV4nvpdw==/com.lt2333.simplicitytools-jaLEW86zYqcNeOMgte9VSw==/base.apk
[ 2023-02-28T11:58:21.068    10132: 16205: 16205 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hooks.MainHook
[ 2023-02-28T11:58:21.134    10132: 16230: 16230 I/LSPosed-Bridge  ] Loading module com.gswxxn.unlockmilink from /data/app/~~ONbYyAKa8Fw5wLoAum_dgg==/com.gswxxn.unlockmilink-L6fLtjsHLq0XI6LTEQuqiw==/base.apk
[ 2023-02-28T11:58:21.136    10132: 16230: 16230 I/LSPosed-Bridge  ]   Loading class com.gswxxn.unlockmilink.hook.HookEntry_YukiHookXposedInit
[ 2023-02-28T11:58:21.151    10132: 16230: 16230 I/LSPosed-Bridge  ] Loading module com.lt2333.simplicitytools from /data/app/~~dbdyKLmJ1377ramV4nvpdw==/com.lt2333.simplicitytools-jaLEW86zYqcNeOMgte9VSw==/base.apk
[ 2023-02-28T11:58:21.153    10132: 16230: 16230 I/LSPosed-Bridge  ]   Loading class com.lt2333.simplicitytools.hooks.MainHook
[ 2023-02-28T11:58:21.266    10132: 16230: 16230 I/LSPosed-Bridge  ] WooBox: Try to Hook [com.milink.service]
[ 2023-02-28T11:58:21.267    10132: 16205: 16205 I/LSPosed-Bridge  ] WooBox: Try to Hook [com.milink.service]
[ 2023-02-28T11:58:29.712    10225: 26920: 27281 I/LSPosed-Bridge  ] FuckCoolApkR: getPackageInfo rejected
[ 2023-02-28T11:58:34.008     1000:  2606:  2960 I/LSPosed-Bridge  ] [D/RPackHook] startActivity 33 CallingUid:2000  CallingPid:5728  UID:1000  PID:2606 userId:0
[ 2023-02-28T11:58:34.008     1000:  2606:  2960 I/LSPosed-Bridge  ] [D/RPackHook] Intent: startActivity { calling=com.android.shell:2000-5728, rc=1000-2606, requestCode=213434728, startFlags=0,intent=Intent { act=android.intent.action.CREATE_DOCUMENT typ=application/zip (has extras) }, extras={ android.intent.extra.TITLE:(java.lang.String)LSPosed_2023-02-28T11:58:34.007771.zip } }

**Comment by zzzqu** [comment]
目前还是有这个问题，猜测是内存泄漏
